In [1]:
import numpy as np

In [2]:
# Create a 4x4 identity matrix
 
identity_4x4 = np.eye(4)
print("\n4x4 Identity Matrix:")
print(identity_4x4)


4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
i2x2 = np.identity(2)
print("2by2 Identity Matrix:\n", i2x2)
 
i3x3 = np.identity(3)
print("3by3 Identity Matrix:\n", i3x3)
 
i4x4 = np.identity(4)
print("4by4 Identity Matrix:\n", i4x4)

2by2 Identity Matrix:
 [[1. 0.]
 [0. 1.]]
3by3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4by4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
i4 = 4*np.identity(2)
i4

array([[4., 0.],
       [0., 4.]])

In [9]:
# Numpy array with shape 2x5 and all elements as zero

# Using zeroes
arr1 = np.zeros((2, 5))
print(arr1)

# using full
arr2 = np.full((2, 5), 0)
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [18]:
# Shape 3x5, all elements 5

# Ones
arr = np.ones((3,5))*5
print(arr)
# Zeroes
arr = np.zeros((3,5))+5
print(arr)

# Full 
arr = np.full((3,5),5)
print(arr)

# Reshape
# Create a 1D array with 15 elements, all set to 5
arr = np.array([5] * 15)
# Reshape the array into a 3x5 shape
arr = arr.reshape((3, 5))
print(arr)

np.full(15,5).reshape(3,5)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [19]:
# Create a NumPy array with random integers between 0-100 and sample size 25
arr = np.random.randint(0, 101, size=25)
print(arr)

[ 8 37 52 10 99 62 67 34 22 65 39 42 99 89 42 43 68 81 20 86 79 54 85 27
 65]


In [22]:
# Create a NumPy array with random float values between 0-100 and sample size 25
arr = np.random.rand(25) * 100
print(arr)

[ 7.60735091 23.12082959  8.47962475 50.49746485 27.86724065 55.61322982
 98.18451094 44.81724351 67.28353962 84.66587551 73.58292672 10.56618188
 16.56552488 70.90224755 19.47775748 42.58671548 78.754285   50.77787485
  3.26373619 27.08655887 96.14644483 72.48595405 34.12235324 95.37974845
 13.5566005 ]


In [24]:
# Create a NumPy array with random float values between 0-100 and sample size 25
np.random.uniform(0,101,size=25)

array([33.77409347, 48.17251449, 13.95622098, 13.15806422, 50.64326494,
       67.57238502,  8.84355819, 38.05209005, 57.93139941, 34.11111705,
       17.0351736 , 42.30164321, 16.84247402,  6.22383616, 13.85324889,
       31.69163582, 41.1148316 , 92.35363713, 20.79819948, 44.66278377,
       26.25537225, 52.31454878, 63.99104552,  0.10932624, 81.64375601])

In [26]:
# Create a numpy array in the shape 2x3 with random integers in the range 0-100.
arr = np.random.randint(0, 101, size=(2, 3))
print(arr)

# Reshape the array in the shape 3x2 and print the updated shape of the resultant array.
# Reshape the array to 3x2
arr = arr.reshape((3, 2))
print(arr)
print(arr.shape)

[[83  7 48]
 [30 40 78]]
[[83  7]
 [48 30]
 [40 78]]
(3, 2)


In [28]:
# Create a 1D array with random integers between 0-1000, size 50, and step 2
arr = np.random.randint(0, 1001, size=50)
print(arr)

[759 197 999 332 338 770 617 326 266 505 252 218 143 802 487 717 726 321
 277 138 140 574 578 598 996 538  36 689 328 645 580  81 487 299 398  96
 616  40 399 609 315 930 204 152 360 634 146 594 728 482]
