In [1]:
import numpy

In [8]:
!pip3 install numpy

133.31s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


Traceback (most recent call last):
  File "/opt/homebrew/opt/python@3.13/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'


In [2]:
import collections

In [4]:
!pip install --upgrade pip

32.16s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


zsh:1: command not found: pip


In [9]:
import sys

In [9]:
!python -m ipykernel install --user

/bin/bash: python: command not found


In [10]:
!pip install ipykernel

Defaulting to user installation because normal site-packages is not writeable


In [11]:
!python -m ipykernel install --user

/bin/bash: python: command not found


In [3]:
import numpy as np

In [2]:
np.full((3,5),5.5)

array([[5.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5]])

In [8]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [1]:
import numpy as np
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.linspace(5,2,2)

array([5., 2.])

In [15]:
# Array with list all elements as float 
np.array([1.0,2.5,2.9,2.5])

array([1. , 2.5, 2.9, 2.5])

In [20]:
# zeroes with 5 rows and 3 columns
import numpy as np
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# ones with 7 rows and 4 columns
np.ones((7,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.array([1,1,1,1,])*44

array([44, 44, 44, 44])

In [25]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [28]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [29]:
np.full((5,4),33)

array([[33, 33, 33, 33],
       [33, 33, 33, 33],
       [33, 33, 33, 33],
       [33, 33, 33, 33],
       [33, 33, 33, 33]])

In [3]:
import pandas as pd

In [13]:
# create a series with 5 company names, count of employee and city
# change the index with State name 

pd.Series(
    [
        [1,'Amazon',2000,'Howrah']
    ],
    index=['WB']
)

# create a DataFrame with 7 fruit names with their prices per kg , availability (Yes/No)
# and change the row as well as column index

pd.DataFrame(
    [
        [1,'Amazon',2000,'Howrah']
    ],
    index=['WB'],
    columns=['s.no','company','num','place']
)

s.no company   num   place
WB     1  Amazon  2000  Howrah

In [14]:
# create a DataFrame with 7 fruit names with their prices per kg , availability (Yes/No)
# and change the row as well as column index
a=pd.DataFrame([[1,'mango',200,'y'],
                [2,'orange',100,'y'],
                [3,'apple',250,'y'],
                [4,'straeberry',400,'n'],
                [5,'plums',300,'n'],
                [6,'grapes',150,'y'],
                [7,'pineapple',100,'y']],index=[101,102,103,104,105,106,107],
               columns=['slno','fruit','price per kg','avilability'])
a

slno       fruit  price per kg avilability
101     1       mango           200           y
102     2      orange           100           y
103     3       apple           250           y
104     4  straeberry           400           n
105     5       plums           300           n
106     6      grapes           150           y
107     7   pineapple           100           y

In [15]:
# create a series with 5 company names, count of employee and city
# change the index with State name 

a = pd.Series([[1,'Amazon',2000,'Howrah'],
                  [2,'Google',1000,'Gurgaon'],
                  [3,'Tesla',5000,'Chennai'],
                  [4,'Hyundai',2500,'Chennai'],
                   [5,'Maruti',5000,'Gurgaon']],
                 index = ['WB','Haryana','TN','TN','Haryana'])
a

WB           [1, Amazon, 2000, Howrah]
Haryana     [2, Google, 1000, Gurgaon]
TN           [3, Tesla, 5000, Chennai]
TN         [4, Hyundai, 2500, Chennai]
Haryana     [5, Maruti, 5000, Gurgaon]
dtype: object

In [4]:
import pandas as pd
df = pd.read_csv('mtcars2.csv')

In [2]:
df

S.No           Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  \
0      1            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   
1      2        Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   
2      3           Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   
3      4       Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   
4      5    Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   
5      6              Valiant  18.1    6  225.0  105  2.76  3.460    NaN   1   
6      7           Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   
7      8            Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   
8      9             Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   
9     10             Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   
10    11            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   
11    12           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   
12    13           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   
13    14          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   
14    15   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   
15    16  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   
16    17    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   
17    18             Fiat 128  32.4    4   78.7   66  4.08  2.200    NaN   1   
18    19          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   
19    20       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   
20    21        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   
21    22     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   
22    23          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   
23    24           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   
24    25     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   
25    26            Fiat X1-9  27.3    4   79.0   66  4.08  1.935    NaN   1   
26    27        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   
27    28         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   
28    29       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   
29    30         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   
30    31        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   
31    32           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   

    am  gear  carb  
0    1     4     4  
1    1     4     4  
2    1     4     1  
3    0     3     1  
4    0     3     2  
5    0     3     1  
6    0     3     4  
7    0     4     2  
8    0     4     2  
9    0     4     4  
10   0     4     4  
11   0     3     3  
12   0     3     3  
13   0     3     3  
14   0     3     4  
15   0     3     4  
16   0     3     4  
17   1     4     1  
18   1     4     2  
19   1     4     1  
20   0     3     1  
21   0     3     2  
22   0     3     2  
23   0     3     4  
24   0     3     2  
25   1     4     1  
26   1     5     2  
27   1     5     2  
28   1     5     4  
29   1     5     6  
30   1     5     8  
31   1     4     2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   S.No        32 non-null     int64  
 1   Unnamed: 1  32 non-null     object 
 2   mpg         32 non-null     float64
 3   cyl         32 non-null     int64  
 4   disp        32 non-null     float64
 5   hp          32 non-null     int64  
 6   drat        32 non-null     float64
 7   wt          32 non-null     float64
 8   qsec        29 non-null     float64
 9   vs          32 non-null     int64  
 10  am          32 non-null     int64  
 11  gear        32 non-null     int64  
 12  carb        32 non-null     int64  
dtypes: float64(5), int64(7), object(1)
memory usage: 3.4+ KB


In [6]:
df.shape

(32, 13)

In [7]:
df.min()

S.No                    1
Unnamed: 1    AMC Javelin
mpg                  10.4
cyl                     4
disp                 71.1
hp                     52
drat                 2.76
wt                  1.513
qsec                 14.5
vs                      0
am                      0
gear                    3
carb                    1
dtype: object

In [8]:
df.max()

S.No                  32
Unnamed: 1    Volvo 142E
mpg                 33.9
cyl                    8
disp               472.0
hp                   335
drat                4.93
wt                 5.424
qsec                22.9
vs                     1
am                     1
gear                   5
carb                   8
dtype: object

In [9]:
df["mpg"].mean()

np.float64(20.090625000000003)

In [10]:
df.mpg.mean()

np.float64(20.090625000000003)

In [15]:
df["mpg"].std()
df.mpg.std()

6.026948052089104

In [11]:
df.describe()

S.No        mpg        cyl        disp          hp       drat  \
count  32.000000  32.000000  32.000000   32.000000   32.000000  32.000000   
mean   16.500000  20.090625   6.187500  230.721875  146.687500   3.596563   
std     9.380832   6.026948   1.785922  123.938694   68.562868   0.534679   
min     1.000000  10.400000   4.000000   71.100000   52.000000   2.760000   
25%     8.750000  15.425000   4.000000  120.825000   96.500000   3.080000   
50%    16.500000  19.200000   6.000000  196.300000  123.000000   3.695000   
75%    24.250000  22.800000   8.000000  326.000000  180.000000   3.920000   
max    32.000000  33.900000   8.000000  472.000000  335.000000   4.930000   

              wt       qsec         vs         am       gear     carb  
count  32.000000  29.000000  32.000000  32.000000  32.000000  32.0000  
mean    3.217250  17.674828   0.437500   0.406250   3.687500   2.8125  
std     0.978457   1.780394   0.504016   0.498991   0.737804   1.6152  
min     1.513000  14.500000   0.000000   0.000000   3.000000   1.0000  
25%     2.581250  16.870000   0.000000   0.000000   3.000000   2.0000  
50%     3.325000  17.420000   0.000000   0.000000   4.000000   2.0000  
75%     3.610000  18.600000   1.000000   1.000000   4.000000   4.0000  
max     5.424000  22.900000   1.000000   1.000000   5.000000   8.0000

In [12]:
df.mpg.describe()

count    32.000000
mean     20.090625
std       6.026948
min      10.400000
25%      15.425000
50%      19.200000
75%      22.800000
max      33.900000
Name: mpg, dtype: float64

In [13]:
df.head(10)

S.No         Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0     1          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1     2      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2     3         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3     4     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     5  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5     6            Valiant  18.1    6  225.0  105  2.76  3.460    NaN   1   0   
6     7         Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7     8          Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8     9           Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9    10           Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   

   gear  carb  
0     4     4  
1     4     4  
2     4     1  
3     3     1  
4     3     2  
5     3     1  
6     3     4  
7     4     2  
8     4     2  
9     4     4

In [18]:
df.tail()

S.No      Unnamed: 1   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  \
27    28    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1   
28    29  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1   
29    30    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1   
30    31   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1   
31    32      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1   

    gear  carb  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [22]:
#drop columns
df.drop(columns = ['S.No'], inplace=True)

In [23]:
df.head()

Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [24]:
df.rename(columns = {"Unnamed: 1" : "Name"}, inplace=True)

In [28]:
df.rename(columns = {"Name": "NAME", "mpg" : "MPG", "cyl": "CYL", "disp": "DISP", "hp":"HP", "drat":"DRAT", "wt": "WT", "qsec":"QSEC","vs":"VS","am":"AM","gear":"GEAR","carb":"CARB"}
             ,inplace = True
         )

In [29]:
df

NAME   MPG  CYL   DISP   HP  DRAT     WT   QSEC  VS  AM  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460    NaN   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200    NaN   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935    NaN   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    GEAR  CARB  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [16]:
# Check how many null values
df.isnull().sum()

S.No          0
Unnamed: 1    0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          3
vs            0
am            0
gear          0
carb          0
dtype: int64

In [35]:
# Replace null values with mean
x=df["QSEC"].mean()
df["QSEC"].fillna(x,inplace = True)

In [36]:
df.head(2)

NAME   MPG  CYL   DISP   HP  DRAT     WT   QSEC  VS  AM  GEAR  \
0      Mazda RX4  21.0    6  160.0  110   3.9  2.620  16.46   0   1     4   
1  Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4   

   CARB  
0     4  
1     4

In [39]:
df["AM"][0]=100

/var/folders/3f/83nwq5m97vng55l8122tx73h0000gn/T/ipykernel_79348/2855786041.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["AM"][0]=100


In [40]:
df.head(2)

NAME   MPG  CYL   DISP   HP  DRAT     WT   QSEC  VS   AM  GEAR  \
0      Mazda RX4  21.0    6  160.0  110   3.9  2.620  16.46   0  100     4   
1  Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0    1     4   

   CARB  
0     4  
1     4

In [41]:
# where clause
df["CYL"]> 6

0     False
1     False
2     False
3     False
4      True
5     False
6      True
7     False
8     False
9     False
10    False
11     True
12     True
13     True
14     True
15     True
16     True
17    False
18    False
19    False
20    False
21     True
22     True
23     True
24     True
25    False
26    False
27    False
28     True
29    False
30     True
31    False
Name: CYL, dtype: bool

In [45]:
df[df["CYL"]> 6]

NAME   MPG  CYL   DISP   HP  DRAT     WT   QSEC  VS  AM  \
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   

    GEAR  CARB  
4      3     2  
6      3     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
28     5     4  
30     5     8

In [50]:
#Sort
df.sort_values(by = "CYL", ascending = True)

NAME   MPG  CYL   DISP   HP  DRAT     WT       QSEC  VS  \
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.600000   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.610000   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.900000   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.700000   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  17.674828   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.010000   1   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.000000   1   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.900000   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.900000   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.520000   1   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  17.674828   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.500000   0   
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.460000   0   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.020000   0   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.440000   1   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.900000   1   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.300000   1   
5               Valiant  18.1    6  225.0  105  2.76  3.460  17.674828   1   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.000000   0   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.500000   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.020000   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.050000   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.410000   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.300000   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.870000   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.840000   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.400000   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.420000   0   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.600000   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.980000   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.600000   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.820000   0   

     AM  GEAR  CARB  
31    1     4     2  
2     1     4     1  
27    1     5     2  
26    1     5     2  
25    1     4     1  
20    0     3     1  
7     0     4     2  
8     0     4     2  
19    1     4     1  
18    1     4     2  
17    1     4     1  
29    1     5     6  
0   100     4     4  
1     1     4     4  
3     0     3     1  
10    0     4     4  
9     0     4     4  
5     0     3     1  
13    0     3     3  
28    1     5     4  
4     0     3     2  
24    0     3     2  
23    0     3     4  
22    0     3     2  
21    0     3     2  
6     0     3     4  
11    0     3     3  
16    0     3     4  
30    1     5     8  
14    0     3     4  
12    0     3     3  
15    0     3     4

In [52]:
    df.sort_values(by = "QSEC", ascending = False)

NAME   MPG  CYL   DISP   HP  DRAT     WT       QSEC  VS  \
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.900000   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.010000   1   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.000000   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.900000   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.440000   1   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.900000   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.610000   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.600000   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.520000   1   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.300000   1   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.000000   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.980000   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.820000   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  17.674828   1   
5               Valiant  18.1    6  225.0  105  2.76  3.460  17.674828   1   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  17.674828   1   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.600000   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.420000   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.400000   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.300000   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.050000   0   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.020000   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.020000   0   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.900000   1   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.870000   0   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.700000   0   
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.460000   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.840000   0   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.500000   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.410000   0   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.600000   0   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.500000   0   

     AM  GEAR  CARB  
8     0     4     2  
20    0     3     1  
7     0     4     2  
19    1     4     1  
3     0     3     1  
10    0     4     4  
2     1     4     1  
31    1     4     2  
18    1     4     2  
9     0     4     4  
13    0     3     3  
14    0     3     4  
15    0     3     4  
17    1     4     1  
5     0     3     1  
25    1     4     1  
12    0     3     3  
16    0     3     4  
11    0     3     3  
22    0     3     2  
24    0     3     2  
1     1     4     4  
4     0     3     2  
27    1     5     2  
21    0     3     2  
26    1     5     2  
0   100     4     4  
6     0     3     4  
29    1     5     6  
23    0     3     4  
30    1     5     8  
28    1     5     4

In [53]:
df.head(5)

NAME   MPG  CYL   DISP   HP  DRAT     WT   QSEC  VS   AM  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0  100   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0    1   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1    1   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1    0   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0    0   

   GEAR  CARB  
0     4     4  
1     4     4  
2     4     1  
3     3     1  
4     3     2

In [4]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable


In [3]:
!pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
  Using cached pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.2-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 24.1.1
    Uninstalling pip-24.1.1:
      Successfully uninstalled pip-24.1.1


In [19]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [10, 20, 30]
})
print(df)
print("=============")
# Sum each column
col_sums = df.apply(sum)
print(col_sums)

   A   B
0  1  10
1  2  20
2  3  30
A     6
B    60
dtype: int64


In [22]:
# Find the max value in each row
print(df)
print("=============")
row_max = df.apply(max, axis=1)
print(row_max)

   A   B
0  1  10
1  2  20
2  3  30
0    10
1    20
2    30
dtype: int64


In [25]:
def custom_func(x):
    return x * 2 + 1

print(df)
print("=============")

df['C'] = df['A'].apply(custom_func)
print(df)

   A   B  C
0  1  10  3
1  2  20  5
2  3  30  7
   A   B  C
0  1  10  3
1  2  20  5
2  3  30  7


In [31]:
from pandasql import sqldf
# Sample DataFrame
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35]
})

print(df)



def run_sql(dfx):
    # Define SQL query
    query = "SELECT name FROM df WHERE age > 28"
    return sqldf(query)
    
print(run_sql(df))

# Run SQL
# result = sqldf(query, globals())
# print(result)

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35
      name
0      Bob
1  Charlie


In [33]:
add1 = lambda x, y: x + y
print(add1(2, 3))  # Output: 5

def add2 (x,y):
    return x+y

print(add2(2, 3))

5
5


In [36]:
nums = [1, 2, 3, 4]
squared = list(map(lambda x: x + x, nums))
print(squared)  # Output: [1, 4, 9, 16]

[2, 4, 6, 8]


In [37]:
even = list(filter(lambda x: x % 2 == 0, nums))
print(even)  # Output: [2, 4]

[2, 4]
